# Change these first
owner: waja # Your GitHub organization or username, where this repository lives
repo: cyconet-upptime # The name of this repository

sites:
  - name: cyconet.org
    url: https://www.cyconet.org
  - name: cyconet.org Blog
    url: https://log.cyconet.org
  - name: 1st Nameserver
    check: "tcp-ping"
    url: $NS1_HOST
    port: 53
  - name: 2nd Nameserver
    check: "tcp-ping"
    url: $NS2_HOST
    port: 53
  - name: Cloud platform
    check: "tcp-ping"
    url: $CLOUD_HOST
    port: 25
  - name: Container platform
    check: "tcp-ping"
    url: $CONTAINER_HOST
    port: 48044
  - name: Traefik router
    url: https://$TREAFIK_URI
  - name: Mail SMTP
    check: "tcp-ping"
    url: $MAIL_HOST
    port: 25
  - name: Mail IMAP
    check: "tcp-ping"
    url: $MAIL_HOST
    port: 143
  - name: Mail SUBMISSION
    check: "tcp-ping"
    url: $MAIL_HOST
    port: 587
  - name: Monitoring platform
    url: https://$BB_HOST/icinga/
  - name: Nextcloud platform
    url: https://$NEXTCLOUD_HOST
  - name: Metrics platform
    url: https://$METRICS_HOST
  - name: Portainer platform
    url: https://$CONTAINER_HOST/ui/
  - name: Paste system
    url: https://$PASTE_HOST
  - name: FTP repository archive
    url: https://$FTP_ARCHIVE_HOST
  - name: Gitlab
    url: https://$GITLAB_HOST
  - name: Development infrastructure
    check: "tcp-ping"
    url: $U9D_HOST
    port: 5000
  - name: Shared hosting
    url: https://$SHARED_HOST
  - name: Homeoffice 1
    check: "tcp-ping"
    url: $HO1_HOST
    port: 48044
  - name: Cloud at Cost 01 (Debian 10)
    check: "tcp-ping"
    url: $CAC01_HOST
    port: 48044
  - name: Cloud at Cost 02 (Debian 10)
    check: "tcp-ping"
    url: $CAC02_HOST
    port: 48044
  - name: Cloud at Cost 03 (Debian 10)
    check: "tcp-ping"
    url: $CAC03_HOST
    port: 48044
  - name: Cloud at Cost 04 (Debian 11)
    check: "tcp-ping"
    url: $CAC04_HOST
    port: 48044
  - name: Cloud at Cost 11 (Ubuntu 20.04 LTS)
    check: "tcp-ping"
    url: $CAC11_HOST
    port: 48044
  - name: Cloud at Cost 21 (Ubuntu 20.04 LTS)
    check: "tcp-ping"
    url: $CAC21_HOST
    port: 48044
  - name: Cloud at Cost 22 (CentOS 8)
    check: "tcp-ping"
    url: $CAC22_HOST
    port: 22
  - name: Oracle Cloud 31 (Oracle Linux 8)
    check: "tcp-ping"
    url: $OC31_HOST
    port: 48044
  - name: Oracle Cloud 32 (Ubuntu 20.04 LTS)
    check: "tcp-ping"
    url: $OC32_HOST
    port: 48044


assignees:
  - waja

status-website:
  # https://github.com/upptime/upptime/discussions/222#discussioncomment-302627
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
    - name: "robots"
      content: "noindex"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /cyconet-upptime
  logoUrl: https://avatars.githubusercontent.com/u/1449568
  name: Cyconet Monitoring
  introTitle: "This sites reflects the status of some assets of cyconet.org."
  introMessage: Just a short overview about the cyconet infrastructure health.
  theme: light
  # https://upptime.js.org/docs/faq/#how-do-i-remove-the-powered-by-upptime-in-the-footer-of-my-website
  navbar:
    - title: Status
      href: /cyconet-upptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: This page is part of [cyconet.org](https://www.cyconet.org)

# https://upptime.js.org/docs/configuration#ci-schedule
workflowSchedule:
  graphs: "0 0 * * *"  # default
  responseTime: "0 23 * * *"  # default
  staticSite: "0 0 * * *"  # default
  summary: "0 0 * * *"  # default
  updateTemplate: "0 1 * * *"  # default: 00:00
  updates: "0 4 * * *"  # default: 03:00
  uptime: "*/5 * * * *"  # default

# https://upptime.js.org/docs/triggers
# Graphs CI: This workflow runs once every day and generates response time graphs from the recorded data
# Response Time CI: This workflow records the reponse time of each endpoint and commits it to git history, which is why it runs once every day
# Setup CI: This workflow is triggered after you edit the configuration file, and runs alls steps: checking uptime, tracking response time, updating the README, and generating graphs
# Static Site CI: This workflow builds and deploys your status page website using GitHub Pages. It reads from your configuration and builds the Svelte/Sapper website, then deploys is to the gh-pages branch and triggers a re-build on GitHub Pages.
# Summary CI: This workflow also runs once every day and updates the README of your project with a summary of the response times and generated graphs
# Update Template CI: This workflow runs once a week and updates the internal code of Upptime to make sure you're always on the latest version
# Uptime CI: This workflow runs once every 5 minutes and checks if your websites are up. If they are down, it creates a new issue in your repository. This same workflow also closes any issues after your websites have come back up

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
